### ISSUE TITLE
Datatypes written with prefix are not expanded

### ISSUE THREAD

**Issue by hmottestad** [awwright/node-rdf#17]
Turtle files with datatypes written with prefixes, eg: "1"^^xsd:number are not expanded to "http://www.w3.org/2001/XMLSchema#number" when parsing.

### What I'm doing
```
let graph = env.createGraph();
let turtleParser = new rdf.TurtleParser();
turtleParser.parse(rdfText, function () {
    graph.forEach(triple => {
        console.log(triple.object.datatype);
    })
}, "", null, graph);
```

### Example turtle

```
@prefix sh: <http://www.w3.org/ns/shacl#>.
@prefix : <http://example.com/>.
@prefix xsd: <http://www.w3.org/2001/XMLSchema#>.

:person1 :age "1"^^xsd:number .

:person1 a :Person.

```

### Prints
xsd:number

### Should print
http://www.w3.org/2001/XMLSchema#number

**Comment by hmottestad** [comment]
I solved this by enabling the string builtins and using .resolve().

However this is a bit inconsistent, because datatype seems to be the only value that is prefixed by default.

**Comment by hmottestad** [comment]
If you do the following:

```
@prefix sh: <http://www.w3.org/ns/shacl#>.
@prefix : <http://example.com/>.
@prefix xsd: <http://www.w3.org/2001/XMLSchema#>.

:person1 :age 1 .

:person1 a :Person.

```

Then 1 gets datatype http://www.w3.org/2001/XMLSchema#integer instead of xsd:integer. So this isn't consistent either.

**Comment by awwright** [comment]
@hmottestad Yeah this might be a bug in the parser, thanks for the detail! There's still a few known problems with this against the standard Turtle test suite, I'll take a look at this!

**Comment by awwright** [comment]
I pushed out a fix, this many more changes than I anticipated.
Converting to N-Triples now outputs:
```
<http://example.com/person1> <http://example.com/age> "1"^^<http://www.w3.org/2001/XMLSchema#number> .
```

I'll close this out since I'm pretty sure this fixes the issue, feel free to open an issue with any further problems.
