### ISSUE TITLE
Package.json missing?

### ISSUE THREAD

**Issue by nicola** [awwright/node-rdf#4]
Hello there I was trying to find the package.json, but I could not find it! Is it on github?

**Comment by ckristo** [comment]
without the package.json file, it is not possible to install the latest dev version from github via npm, cf. https://github.com/npm/npm/issues/7232

I tried to install the latest version of node-rdf via npm from github: `npm install --save git+ssh://git@github.com:Acubed/node-rdf`

**Comment by Acubed** [comment]
@ckristo Like a lot of repositories, this isn't an npm package as such, and it doesn't really make sense to talk about it that way until a release is tagged. It's first and foremost an ECMAScript library for Node.js. The issue seems to be a problematic assumption with npm itself.

**Comment by ckristo** [comment]
@Acubed yea, I fear so ... if you do not want to add it, that's ok; it would've eased packaging the latest development version and therefore would lower the border for contributions...

Other libraries I've explored have added it to the repo (although they are not a npm package per se and are designed to work with other JS engines than node), cf. [rdflib.js](https://github.com/linkeddata/rdflib.js/), [rdfstore-js](https://github.com/antoniogarrote/rdfstore-js), [rdf-ext](https://github.com/zazukoians/rdf-ext)
