### ISSUE TITLE
Release latest version to npm

### ISSUE THREAD

**Issue by ckristo** [awwright/node-rdf#7]
Hi,

I've installed node-rdf via npm and encountered that the latest release there does not implement graph.removeMatches yet .. Could you release the latest commit as version to npm? Thanks.

Kind regards,
Chris

**Comment by ckristo** [comment]
In the meantime, I tried to install the latest dev version via npm from github, but that seems not possible because of the missing package.json file (cf. issue #4)

**Comment by Acubed** [comment]
Can you paste in the exact error you're getting?

**Comment by Acubed** [comment]
v3.0.1 is already pushed to npm, so I'll need to tag a minor version bump later today.

**Comment by ckristo** [comment]
@Acubed no exact error, I simply encountered that the latest version in npm (v3.0.1) is several commits (one implemented graph.removeMatches). It would be great if you could release a new minor version with the latest commits.

**Comment by Acubed** [comment]
@ckristo You can checkout commit 8589c2990 which has only removeMatches, but without the domain checking that's causing problems as in Issue #8

**Comment by awwright** [comment]
Done https://www.npmjs.com/package/rdf/v/4.0.0
