### ISSUE TITLE
Use "Builtins" only?

### ISSUE THREAD

**Issue by ckristo** [awwright/node-rdf#8]
Hi,

I try to use the "Builtins" feature of node-rdf to make the resulting code more readable, but I cannot create a triple by simply calling `rdfEnvironment.createTriple(string, string, string)` -- this triggers an error because the Triple constructor checks the type of the arguments (cf. RDFNode.js:29ff). Is this intended? Am I using the "Builtins" feature wrong? Or should this be possible? Is there another way how I can create a triple with the "Builtins" feature?

Kind regards,
Chris

**Comment by Acubed** [comment]
Can you provide a simple file that demonstrates the problem, and provide expected and actual output?

**Comment by ckristo** [comment]
Sure, here's the error ::
````
/usr/local/bin/node rdf_example.js
/home/ckristo/node-rdf-example/node_modules/rdf/lib/RDFNode.js:29
	if(!(s instanceof api.RDFNode)) throw new Error('Triple subject is not an RDF
	                                      ^
Error: Triple subject is not an RDFNode
    at new Triple (/home/ckristo/node-rdf-example/node_modules/rdf/lib/RDFNode.js:29:40)
    at RDFEnvironment.exports.RDFEnvironment.createTriple (/home/ckristo/node-rdf-example/node_modules/rdf/lib/RDFEnvironment.js:33:9)
    at /home/ckristo/node-rdf-example/rdf_example.js:19:26
    at Turtle.parse (/home/ckristo/node-rdf-example/node_modules/rdf/lib/TurtleParser.js:66:36)
    at /home/ckristo/node-rdf-example/rdf_example.js:15:12
    at fs.js:334:14
    at FSReqWrap.oncomplete (fs.js:95:15)

Process finished with exit code 1
````
and here's the snippet causing it ::
````js
var fs  = require('fs');
var rdf = require('rdf');

// - extends built-in JS types for use with node-rdf
rdf.setBuiltins();

var rdfEnv = rdf.environment;

// - load RDF document file
fs.readFile('foaf.ttl', function (err, data) {
    if (err) { /* error handling */ }

    // - parse the loaded file
    var parser = new rdf.TurtleParser();
    parser.parse(data.toString(), function(graph) {
        var me = 'http://kindl.io/christoph/foaf.rdf#me';

        // - add new properties
        graph.add(rdfEnv.createTriple(me, 'foaf:mbox', 'mailto:e0828633@student.tuwien.ac.at'));
        graph.add(rdfEnv.createTriple(me, 'foaf:nick', 'ckristo'));

        console.log(graph.toString());
    });
});
````

**Comment by ckristo** [comment]
I'd expected that I can use a string instead of an `RDFNode` everywhere (so that I do not need to wrap the strings into `NamedNode` instances)

**Comment by ckristo** [comment]
Btw.: I've used v3.0.1 with Builtins and it worked -- so maybe the 'domain-checking' branch merged in January didn't consider the Builtins feature.

```js
if(!(s instanceof api.RDFNode)) throw new Error('Triple subject is not an RDFNode');
if(!(p instanceof api.RDFNode)) throw new Error('Triple predicate is not an RDFNode');
if(!(o instanceof api.RDFNode)) throw new Error('Triple object is not an RDFNode');
```
What about checking if the function property `nodeType` is available and returns either `IRI` or `BlankNode` for subject and predicate, and `IRI`, `BlankNode` or `TypedLiteral` and `PlainLiteral` for the object?

It would remain to complete string.nodeType() though (see the things commented out here) ::
````js
	nodeType: _( function() {
		//if(this.type) return 'TypedLiteral';
		//if(this.language || this.indexOf(' ') >= 0 || this.indexOf(':') == -1 ) return 'PlainLiteral';
		if(this.substr(0,2) == '_:') return 'BlankNode';
		return 'IRI';
	}),
````

**Comment by Acubed** [comment]
@ckristo This is in the current master, and not npm right?

My own tests are failing with your exact error, so unfortunately I can't release v3.1.0 until this gets fixed D:

Perhaps I'll add a nodeType() function that can accept anything, and returns `null` or similar if it's not any RDFNode. Hmmm.

For maximum portability, I would suggest not using the builtins, though.

I'll try to have a fix worked out soon!

**Comment by awwright** [comment]
The latest test suite includes extensive tests both with a clean process and with builtins set. This _should_ be fixed. Open a new issue with any further problems.
