### ISSUE TITLE
PrefixMap.shrink may return incorrect result in case of overlapping namespace URIs

### ISSUE THREAD

**Issue by stefan-guggisberg** [awwright/node-rdf#9]
if namespace uri's are overlapping, like in the example below, PrefixMap.shrink sometime returns incorrect results, depending on the order of namespace declarations, e.g.

@prefix xmp: http://ns.adobe.com/xap/1.0/ .
@prefix xmpMM: http://ns.adobe.com/xap/1.0/mm/ .
@prefix xmpRights: http://ns.adobe.com/xap/1.0/rights/ .

turtleParser.environment.prefixes.shrink('http://ns.adobe.com/xap/1.0/mm/DocumentID') -> 'xmp:mm/DocumentID' instead of 'xmpMM:DocumentID'

**Comment by awwright** [comment]
Ahh, good catch

**Comment by awwright** [comment]
I forgot to comment on this...

The referenced commit seems to check that there is no `/` or `#` in the result, however this isn't necessarily true according to <https://www.w3.org/TR/curie/>:

> All of the following are valid CURIEs — even though they are not valid QNames — and they take advantage of the fact that the part after the colon no longer needs to conform to the rules for element names:
>
>home:#start
>joseki:
>google:xforms+or+'xml+forms'

A solution to accommodate this would be to find the longest matching substring.

**Comment by jimsmart** [comment]
Hi,

I believe I have a better patch for this that I'm just testing - it always matches from longest to shortest namespace.

**Comment by awwright** [comment]
The library in `master` now searches for the longest substring match:
```
> rdf.environment.setPrefix('xmp', 'http://ns.adobe.com/xap/1.0/');
> rdf.environment.setPrefix('xmpMM', 'http://ns.adobe.com/xap/1.0/mm/');
> rdf.environment.setPrefix('xmpRights', 'http://ns.adobe.com/xap/1.0/rights/');
> rdf.environment.prefixes.shrink('http://ns.adobe.com/xap/1.0/mm/DocumentID');
'xmpMM:DocumentID'
```
(tested in every order)

I'll close this out since it appears to solve the problem, feel free to follow-up or open a new issue. I'll have a release out soon.
